-- Historical no-op migration.
-- Some SQLite versions used in local environments do not support
-- "DROP COLUMN IF EXISTS" syntax, which can block startup migrations.
-- Migration 011 re-adds preview_image_url, so keeping this migration as a
-- no-op preserves the final schema without compatibility issues.
